---
hostname: R2
interfaces:
    - name: GigabitEthernet2
      address: 10.10.12.2/24
      desc: Link to R1
    - name: GigabitEthernet3
      address: 10.10.23.1/24
      desc: Link to R3
ospf_networks:
    - network: "10.10.12.2 0.0.0.255"
      area: "0"
      process_id: "1"
    - network: "10.10.23.1 0.0.0.255"
      area: "0"
      process_id: "1"